config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  
  resources :projects do
    resources :comments
  end

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :project
  validates :body, presence: :true

  def owner?(user)
    self.user == user
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :name, presence: true

  before_create :set_default_status

  enum status: {
    created: 'Created',
    in_progress: 'In Progress',
    completed: 'Completed',
    stalled: 'Stalled'
  }

  def set_default_status
    self.status ||= 'Created'
  end

  def owner?(user)
    self.user == user
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :projects
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_comment, only: %i[show edit update destroy]
  before_action :check_user, only: %i[edit update destroy]

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @project = Project.find(params[:project_id])
    @comment = @project.comments.build
  end

  def edit
  end

  def create
    @comment = @project.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to project_url(@project), notice: 'Comment was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to project_url(@project), notice: 'Comment was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def project_comments
    @comments = @project.comments
    render 'index'
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :user_id, :created_at, :updated_at).merge(project_id: params[:project_id])
  end

  def check_user
    return if @comment.owner?(current_user)

    redirect_to @project, alert: "You don't have permission to access this resource."
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[show edit update destroy]
  before_action :check_user, only: %i[edit update destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = current_user.projects.build
  end

  def edit
  end

  def create
    @project = current_user.projects.build(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @project.update(project_params)
      redirect_to project_url(@project), notice: 'Project was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(:name, :status, :description)
  end

  def check_user
    return if @project.owner?(current_user)

    redirect_to @project, alert: "You don't have permission to access this resource."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/comments/_comment.html.erb
<div class= "card mb-4">
  <div class= "card-body pt-4">
    <p class="card-text font-weight-bold"> Comment: <%= comment.body %> </p>
    <p class="card-text font-weight-bold"> Author: <%= comment.user.email %> </p>
    <p class="card-text font-weight-bold"> Date: <%= comment.updated_at %> </p>
    <% if current_user == comment.user %>
      <%= link_to "Edit Comment", edit_project_comment_path(@project, comment) %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="card">
  <div class="card-body p-4">
    <%= form_with(model: [ @project, @comment ]) do |form| %>
    <%= form.hidden_field :user_id, value: current_user.id %>
      <% if comment.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
            <% comment.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="pt-2">
        <%= form.label "Add your comment", class: "form-label"  %>
        <%= form.text_area :body, class: "form-control rounded"%>
      </div>
      
      <div class="form-group pt-4">
        <%= form.submit class: "btn btn-primary rounded" %>
      </div>
    <% end %>
  </div>
</div> 

app/views/comments/edit.html.erb
<div class="container-fluid pt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3 text-center pt-4">
      <h1 class="display-5">Editing comment</h1>

      <%= render "form", comment: @comment %>

      <div class="pt-4">
        <%= link_to "Back to project", project_path(@project) %>
      </div>
    </div>
  </div>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<div class="container-fluid pt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3 text-center pt-4">
      <h1 class="display-5">New comment</h1>

      <%= render "form", comment: @comment %>

      <div class="pt-4">
         <%= link_to "Back to project", project_path(@project) %>
      </div>
    </div>
  </div>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<br>
<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project Management Conversation App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  
  <body class="bg-light">
    <div class="container-fluid pt-5">
      <% if user_signed_in? %>
        <div style="float: right; margin: 10px;">
          <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
        </div>
      <% end %>
       <%= yield %> 
    <div>
          
          

  </body>
</html>

app/views/projects/_form.html.erb
<div class="card">
  <div class="card-body p-4">
    <%= form_with(model: project) do |form| %>
      <% if project.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

          <ul>
            <% project.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="pt-2">
        <%= form.label :name, class: "form-label"  %>
        <%= form.text_field :name, class: "form-control rounded"%>
      </div>
    
      <div class="pt-2">
        <%= form.label :description,  class: "form-label" %>
        <%= form.text_area :description, class: "form-control rounded", rows: 5 %>
      </div>
    
      <div class="form-group pt-4">
        <%= form.submit class: "btn btn-primary rounded" %>
      </div>
    <% end %>
   </div>
  </div>  

app/views/projects/_project.html.erb
  <h2 class="card-title display-2"><%= project.name %></h2>
  <p class="card-text pt-4"><strong>Status:</strong> <%= project.status.humanize %></p>
  <p class="card-text text-justify pb-4"><strong>Description:</strong> <%= project.description %></p>

app/views/projects/edit.html.erb
<div class="container-fluid pt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3 text-center pt-2">
      <h1 class="display-5 mb-4">Editing project</h1>

      <%= form_with(model: @project, local: true) do |form| %>
      <div class="form-group">
          <%= form.label :status %>
          <%= form.select :status, Project.statuses.keys.map { |s| [s.humanize, s] } %>
        </div>
        <br>

      <div>
        <%= render "form", project: @project, form: form %>
      <div>


        <div class="mt-4">
          <%= link_to "Back to project", @project %> |
          <%= link_to "Back to projects", projects_path %>
        </div>
      <% end %>
    </div>
  </div>
</div>     

app/views/projects/index.html.erb
<p style="color: green"><%= notice %></p>

<div class=container>
  <h1 class="display-1 text-center mb-4">All Projects</h1>

    <% @projects.each do |project| %>

    <%= content_tag :div, class: "card mb-20 ", style: "margin-bottom: 20px;" do %>
      <%= content_tag :div, class: "card-body" do %>
        <%= render project %>
        <p>
          <%= link_to "Go to project", project %>
        </p>
        <% end %>
      <% end %>
    <% end %>


  <%= link_to "Create a new project", new_project_path, class: "btn btn-primary", role: "button" %>

</div>

app/views/projects/new.html.erb
<div class="container-fluid pt-5">
  <div class="row">
    <div class="col-md-6 offset-md-3 text-center pt-2">
      <h1 class="display-5">New project</h1>

      <%= render "form", project: @project %>

      <div class="mt-4">
        <%= link_to "Back to projects", projects_path %>
      </div>
 

app/views/projects/show.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red"><%= alert %></p>

<div class = "container">
  <%= render @project %>

  <h2 class= "mb-4 display-6">Project's Comments</h2>
  
  <% @project.comments.each do |comment| %> 
    <%= render comment %>
  <% end %>
 
  <%= button_to "Add Comment", new_project_comment_path(@project), method: :get, class: "btn btn-primary btn-sm" %>

  <div class="mt-4">
    <%= link_to "Back to projects", projects_path %>
  </div>

  <div class="mt-4 btn-group gap-4 btn-group-horizontal" ">
    <%= button_to "Edit this project", edit_project_path(@project), method: :get, class: "btn btn-secondary" %>
    <%= button_to "Delete this project", @project, method: :delete, class: "btn btn-danger" %>
  </div>
</div>